config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts

  root 'posts#index'

  get 'comment' => 'comments#index'

  get '/:name' => 'posts#user_posts', as: :user_posts

# #Practice stuff below
  get 'index' => 'practice#index'

  get 'about' =>'practice#about'

  post 'index' => 'practice#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user

	paginates_per 3
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

		mount_uploader :avatar, AvatarUploader

     has_many :posts
     has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # USER'S POST
  def user_posts
    @user = User.find_by(username: params[:name])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def index
  	@name = params[:name]
  end

  def about
  	#PARAMS FOR LINKS AND COLOR
  	@color = params[:color]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field subheader">
       <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
  
    <%= form.text_area :comment_entry, id: :comment_comment_entry, class: "comment_box" %>
  </div>

  <div class="field subheader">
    <% if @post != nil %>

      <%= form.hidden_field :post_id, value: @post.id %>
    <% else %>
      <%= form.hidden_field :post_id, value: @comment.post_id %>
    <% end %>

  </div> 

  <div class="actions comment_btn">
    <%= form.submit class: "btn btn-warning" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class ="wrapper1">
      <div class="container">

  <!-- NAV -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">

  <!-- NAV BRAND -->
         <%= link_to "Esteban's Blog", root_path, class: "navbar-brand" %>
          

  <!-- NAV TOGGLE BUTTON -->
           <button class="nav-btn pull-right navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="true" aria-label="Toggle navigation">
          <span class="glyphicon glyphicon-menu-hamburger"></span>
          </button>

          <div class=" collapse navbar-collapse" id ="navbarTogglerDemo02" >


   <!-- LINKS IN NAV -->
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">

              <li class="nav-item">
            <%= link_to "New Post", new_post_path, class: "nav-link" %>
              </li>
              

              <li class="nav-item">
               <%= link_to "Posts", root_path, class: "nav-link" %> 
              </li>
             
<!-- Devise -->
               <% if user_signed_in? %>
                   <!-- Edit Profile -->
                  <li class="nav-item">
                      <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>

                  </li>

                  <li class="nav-item">
                  <!-- Devise Sign Out -->   
                         <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>

                  </li>

                  <li class="nav-item">
                        <!-- AVATAR -->
                    <% if current_user.avatar.url != nil %>
                   <%= image_tag current_user.avatar.url, class: "nav-pic" %>
                   <% end %>

                  </li>

              <% end %>
            </ul>
    
            </div>

     
        </nav>
     
    	 <%= yield %>
   	  
     
         <!-- Credits -->
     <hr id="bottom-hr" class="line">
    <p class="bottom center_text"> &copy;EsteBrand 2017</p>
     </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<hr class="line">

<div class = "well">
  <div class="row">
    <%= form_with(model: post, local: true) do |form| %>
      <% if post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field col col-md-6 col-sm-6 col-xs-6">
        <%= form.label :title, class: "subheader" %>
        <%= form.text_field :title, id: :post_title%>
      </div>

      <div class="field col col-md-6 col-sm-6 col-xs-6">
       <%= form.hidden_field :user_id, value: current_user.id %>
      </div>
    </div>
    <div class="row">


      <div class="field col col-md-12 col-sm-12 col-xs-12">
        <%= form.label :blog_entry, class: "subheader" %>
        <%= form.text_area :blog_entry, id: :post_blog_entry %>
      </div>
    </div>
    <div class="row">

      <div class="actions col col-md-12 col-sm-12 col-xs-12">
        <%= form.submit class: "btn btn-info center-block comment_btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class = "wrapper">
  <p id="notice"><%= notice %></p>

  <h1>Posts</h1>
  <p class="center_text"> Welcome <%= current_user.username %></p>
   
      <% @posts.each do |post| %>

      <div class="well">
          <div class="row">

              <p class="col col-md-4 col-sm-4 col-xs-4 title"><%= post.title  %></p>

           <!-- Avatar -->
             <p class="col col-md-1 col-sm-1 hidden-xs">
              <% if post.user.avatar.url != nil %>
              <%= image_tag post.user.avatar.url, class: "avatar" %>
              <% end %>
            </p>

              <p class="col col-md-3 col-sm-3 col-xs-4"><strong class="subheader">Author: </strong><%= link_to post.user.username, user_posts_path(name: post.user.username) %>
              </p>

       

              <p class="col col-md-4 col-sm-4 col-xs-4"><strong class="subheader">Created On: </strong><%= post.created_at.strftime("%d %b. %y")  %></p>

          </div>
              <hr class="line">
          <div>
            <p ><%= post.blog_entry.html_safe %></p>
          </div>
            <hr class="line">

          <div class="row">

            <p class="col col-md-4 col-sm-4 col-xs-4"><%= link_to 'Show', post, class: "btn btn-info center-block" %></p>
        
          <%if post.user_id == current_user.id %>    
            <p class="col col-md-4 col-sm-4 col-xs-4 ">

              <%= link_to 'Edit', edit_post_path(post),class: "btn btn-primary center-block" %>            
              </p>
            
            <p class="col col-md-4 col-sm-4 col-xs-4">
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-warning center-block"  %> 
              </p>
            <% end %>
          
          </div>

        </div>
   <% end %>
   <!-- Paginate --> 
    <p class="center_text nav-link" 
      <%= paginate @posts %> >
    </p>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1 class="center_text"><%= @post.title %></h1>
<hr class="line">

<div class="well">
	<p id="notice"><%= notice %></p>

	<div class="row">
			<p class="col col-md-3 col-sm-3 col-xs-3">
			  <strong class="subheader">Title:</strong>
			  <%= @post.title %>
			</p>

			<p class="col col-md3 col-sm-3 col-xs-3">
			  <strong class="subheader">Author:</strong>
			  <%= link_to @post.user.username, user_posts_path(name: @post.user.username) %>
			 </p>

			<p class="col col-md-2 col-sm-2 col-xs-2">
			
			 <% if @post.user.avatar.url != nil %>
			  <%= image_tag @post.user.avatar.url, class: "avatar" %></p>
			  <% end %>
			</p>



				<p class="col col-md-4 col-sm-4 col-xs-4">
			  <strong class="subheader">Created On:</strong>
			  <%= @post.created_at.strftime("%d %b. %y") %>
			</p>

	</div>

	<p>
	  <strong class="subheader"></strong>
	  <%= @post.blog_entry.html_safe %>
	</p>
	
</div>	
	<hr class="line">
	

	<h4>Leave a Comment Below</h4>

	<div id="comment">
	  <%= render 'comments/form', comment: @comment %>
	<hr>

			<% @post.comments.each do |c| %>
					<div class="well">
							<!-- AVATAR -->
						<% if current_user.avatar.url != nil %>
						 <p><%= image_tag c.user.avatar.url, class: "avatar" %></p>
						 <% end %>

						<p><%= link_to c.user.username, user_posts_path(name: c.user.username) %> said...<br /></p>

				


						<div class="well comment-color">
							<p><%= c.comment_entry.html_safe %><br /></p>
						</div>
						<%if @post.user_id == current_user.id %>

						<div class="row">	

						<p class="col col-md-9 col-sm-8 col-xs-5">
								Created on <%= c.created_at.strftime("%d %b. %y") %></p>
							<p class="col col-md-1 col-sm-2 col-xs-3">
							<%= link_to 'Edit', edit_comment_path(id: c.id), class: "btn btn-info" %>	</p>
							<p class="col col-md-2 col-sm-2 col-xs-4">
              <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-warning center-block"  %> 
           		 </p>
              
            </div>
						<% end %>
					</div>
			<% end %>

	</div>
	

app/views/posts/user_posts.html.erb
<h1>All Posts by <%= @user.username %></h1>
<% if @user.avatar.url !=nil %>
<p><%= image_tag @user.avatar.url, class: 'avatar center_text' %></p>
<% end %>


<% @user.posts.each do |post| %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="well">
        <h3><%= post.title %></h3>
        <p><em>posted on <%= post.created_at.strftime("%B %e, %Y at %l:%M %p") %></em></p>
        <p>
          <%= post.blog_entry.html_safe %>
        </p>
        <p>
          <%= link_to 'Show', post, class: "btn btn-info" %> 
          <% if current_user.id == post.user_id %>
	    <%= link_to 'Edit', edit_post_path(post), class: "btn btn-warning" %> 
	    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
	  <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/practice/about.html.erb
<style>
	

#color_me_in {
	background-color: <%= @color %>;
	color: white;


}

h2{
	padding: 15%;
}

.box{
	width: 70%;
	margin-left: 15%;
	margin-right: 15%;
	height: 100%;
	font-family: helvetica, arial, sans-serif;

}

</style>


<div  id = color_me_in class = box >

<h2> <%= @color.upcase %> BOX ACTIVATED! </h2>

</div>

<div class = box >
<%= form_tag index_path do %>

		<p> <%= text_field_tag :name, nil, placeholder: "What's your name?" %> </p>
		<p><%= submit_tag :submit %></p>

<% end %>

</div>

app/views/practice/index.html.erb
<style>
	


</style>


<h1> Choose a Color!</h1>

<p>	<%= link_to "Red",about_path(color: "red") %> </p>

<p><%= link_to "Blue", about_path(color: "blue") %></p>

<p><%= link_to "Green", about_path(color: "green") %></p>

<p><%= link_to "Orange", about_path(color: "orange") %></p>

<% if !@name.blank? %>
	<h3>Welcome Back <%= @name.capitalize %>!</h3>
<% end %>